package app.allowmate

fun statusText(code: String): String = when (code) {
    "NOT_CHECKED" -> "尚未检查"
    "DEMO_READY" -> "模拟环境已就绪，尚未检查"
    "PRESENT_CURRENT_CHECK" -> "本次检查已收录"
    "ADDED_VERIFIED" -> "本次添加后查询已收录"
    "HOME_PINNED_VERIFIED" -> "家宽已固定保护，写后查询通过"
    "MOBILE_SLOT_VERIFIED" -> "手机网段已同步，家宽保护核对通过"
    "HOME_GUARD_FAILED" -> "家宽保护异常，已暂停；请核查平台"
    "HOME_SETUP_REQUIRED" -> "请连接家宽完成固定保护初始化"
    "SLOT_CONFLICT" -> "手机或家宽槽位被其他条目占用，已暂停"
    "SLOT_INVALID" -> "平台槽位结构异常，已暂停"
    "SLOT_VERIFY_FAILED" -> "槽位写后核对失败，已暂停；请核查平台"
    "OBSERVED_MISSING" -> "观察到当前 /24 未收录"
    "EGRESS_UNVERIFIED" -> "出口未验证，自动写入已阻止"
    "UNSAFE_SERVER_ADD" -> "服务端并发安全未确认，禁止添加"
    "CAPACITY_FULL" -> "平台已满，保留所有已有条目"
    "MOBILE_BUDGET_FULL" -> "流动预算已用完，安全替换不支持"
    "FIXED_BUDGET_FULL" -> "固定预算已用完，请调整预算或本地关联"
    "BUDGET_CONFLICT" -> "预算与平台已有条目冲突"
    "FIXED_DRIFT" -> "固定项出口变化，等待用户确认"
    "CONCURRENT_CHANGE" -> "平台或出口发生变化，本次操作已停止"
    "VERIFY_FAILED" -> "写后验证失败，请核查平台；不会自动删除"
    "RATE_LIMITED" -> "仍在限频或退避期，请稍后检查"
    "CACHED_OBSERVATION" -> "沿用最近一次观察，非当前检查"
    "AUTH_PAUSED", "HTTP_401", "HTTP_403" -> "鉴权失败，自动请求暂停；请更新本地凭据"
    "HTTP_429" -> "服务端限频，等待 Retry-After / 退避"
    "NO_TOKEN" -> "未配置本地凭据，未发起账户请求"
    "TOKEN_SAVED" -> "凭据已加密保存，尚未检查"
    "SLOT_CONFIGURED" -> "Po0 配置已保存，恢复检查后生效"
    "PAUSED" -> "已暂停"
    "BUSY" -> "检查进行中"
    "CANCELLED_NETWORK_OR_SETTINGS", "NETWORK_CHANGED" -> "网络或设置变化，旧检查已取消"
    "INVALID_RESPONSE" -> "响应结构无效，未执行写入"
    "PLATFORM_DISABLED" -> "平台未启用白名单或返回无效状态"
    "PROBE_RUNNING" -> "正在探测国内出口"
    "PROBE_OBSERVED" -> "已观察国内站点出口"
    "PROBE_INVALID_RESPONSE", "PROBE_FAILED" -> "国内出口响应无效或检查失败"
    "PROBE_IPV6_ONLY" -> "国内站点仅返回 IPv6，尚无 IPv4 /24 证据"
    "STORAGE_RECOVERY_REQUIRED" -> "本地状态无法读取；已安全暂停，请重新配置"
    "NETWORK_TLS_OR_RESPONSE_ERROR", "NETWORK_OR_STORAGE_ERROR" -> "网络、TLS 或响应异常；已进入退避"
    else -> "检查未完成（${code.take(48)}）"
}
