package app.allowmate

fun statusText(code: String): String = when (code) {
    "UNTRUSTED_PATH" -> "检测到 VPN 或代理，已跳过本次检查"
    "UNMANAGED" -> "未授权本机管理"
    "AUTHORIZED_LOCAL" -> "已授权，等待检查"
    "IDENTITY_REQUIRED" -> "未绑定 Wi-Fi，可手动更新"
    "LEGACY_UNINITIALIZED" -> "旧配置需要重新授权"
    "LEGACY_RECONCILE" -> "旧配置等待核对"
    "MIGRATED_CELLULAR_ONLY" -> "已迁移，仅在移动数据下更新"
    "SLOT_NOT_LOCAL" -> "未允许本机自动更新"
    "TEMPORARY_HOLD" -> "临时保留中"
    "SLOT_CURRENT" -> "已是最新"
    "SLOT_UPDATED" -> "已更新并核对"
    "EXTERNAL_CHANGE" -> "检测到外部修改，本机不接管"
    "COVERED_OTHER_SLOT" -> "当前出口已在其他槽位，此槽未更新"
    "NO_TARGET", "MOBILE_MATCH" -> "没有需要更新的槽位"
    "UNKNOWN_WIFI" -> "未知 Wi-Fi，未更新"
    "WIFI_UNAVAILABLE" -> "无法读取 Wi-Fi 信息"
    "WIFI_SECURITY_CHANGED" -> "Wi-Fi 加密方式已变化，已停止自动更新"
    "IDENTITY_AMBIGUOUS" -> "网络匹配到多个槽位，请检查绑定"
    "PENDING_REVIEW" -> "上次写入待确认，下次检查会先核对"
    "PENDING_CONFIG_CHANGED" -> "配置已变化，请重新授权此槽"
    "RECOVERED_VERIFIED" -> "上次写入已确认生效"
    "RECOVERED_NOT_APPLIED" -> "上次写入未生效，将重新判断"
    "MANUAL_EXPIRED" -> "确认已过期，请重新操作"
    "AUTHORIZATION_REQUIRED" -> "请先打开「授权本机管理」"
    "CONFIG_QUERY_FIRST" -> "请先检查连接，再保存授权"
    "CONFIG_MOBILE_LIMIT" -> "每台手机只能有一个自动移动槽"
    "REBIND_REQUIRED" -> "Wi-Fi 名称已变化，请重新绑定"
    "ACCOUNT_MISMATCH" -> "账户信息不一致，已停止操作"
    "DEMO_SCENARIO_0" -> "演示：住宅"
    "DEMO_SCENARIO_1" -> "演示：住宅重新拨号"
    "DEMO_SCENARIO_2" -> "演示：移动数据"
    "DEMO_SCENARIO_3" -> "演示：办公室"
    "DEMO_SCENARIO_4" -> "演示：新接入点待确认"
    "DEMO_SCENARIO_5" -> "演示：缺少权限"
    "DEMO_SCENARIO_6" -> "演示：槽位被占用"
    "NOT_CHECKED" -> "尚未检查"
    "DEMO_READY" -> "演示数据已就绪"
    "PRESENT_CURRENT_CHECK" -> "当前出口已在白名单"
    "ADDED_VERIFIED" -> "已添加并核对"
    "HOME_PINNED_VERIFIED" -> "家宽已固定"
    "MOBILE_SLOT_VERIFIED" -> "手机网段已同步"
    "HOME_GUARD_FAILED" -> "家宽保护异常，已暂停"
    "HOME_SETUP_REQUIRED" -> "请连接家宽完成初始化"
    "SLOT_CONFLICT" -> "槽位占用与授权不符，请核对后重新授权"
    "SLOT_INVALID" -> "平台槽位异常，已暂停"
    "SLOT_VERIFY_FAILED" -> "写入后核对失败，已暂停"
    "OBSERVED_MISSING" -> "当前出口不在白名单"
    "EGRESS_UNVERIFIED" -> "出口未验证，未写入"
    "UNSAFE_SERVER_ADD" -> "平台不支持安全添加"
    "CAPACITY_FULL" -> "白名单已满"
    "MOBILE_BUDGET_FULL" -> "移动名额已用完"
    "FIXED_BUDGET_FULL" -> "固定名额已用完"
    "BUDGET_CONFLICT" -> "名额与平台记录冲突"
    "FIXED_DRIFT" -> "固定出口已变化，等待确认"
    "CONCURRENT_CHANGE" -> "平台或出口有变化，已停止"
    "VERIFY_FAILED" -> "写入后核对失败，请检查平台"
    "RATE_LIMITED" -> "请求太频繁，请稍后再试"
    "CACHED_OBSERVATION" -> "显示的是上次结果"
    "AUTH_PAUSED", "HTTP_401", "HTTP_403" -> "Token 无效，已暂停自动检查"
    "HTTP_429" -> "平台限流，稍后自动重试"
    "NO_TOKEN" -> "未添加 Token"
    "TOKEN_SAVED" -> "Token 已保存，尚未检查"
    "SLOT_CONFIGURED" -> "配置已保存"
    "PAUSED" -> "已暂停"
    "BUSY" -> "正在检查"
    "CANCELLED_NETWORK_OR_SETTINGS", "NETWORK_CHANGED" -> "网络已变化，本次检查已取消"
    "INVALID_RESPONSE" -> "平台返回异常，未写入"
    "PLATFORM_DISABLED" -> "平台未启用白名单"
    "PROBE_RUNNING" -> "正在查询"
    "PROBE_OBSERVED" -> "已获取"
    "PROBE_INVALID_RESPONSE", "PROBE_FAILED" -> "查询失败"
    "PROBE_IPV6_ONLY" -> "仅返回 IPv6 地址"
    "STORAGE_RECOVERY_REQUIRED" -> "本地数据无法读取，原文件已保护；请勿清除应用数据"
    "NETWORK_TLS_OR_RESPONSE_ERROR", "NETWORK_OR_STORAGE_ERROR" -> "网络异常，稍后自动重试"
    else -> "检查未完成（${code.take(48)}）"
}

/** Display-only network names; the controller's raw kind strings feed core decisions and stay unchanged. */
fun networkText(kind: String): String = when {
    kind == "Wi-Fi" -> "Wi-Fi"
    kind.startsWith("移动数据") -> "移动数据"
    kind.startsWith("VPN") -> "VPN"
    kind == "其他网络" -> "其他网络"
    else -> "未连接"
}
